### ISSUE TITLE
Pendências

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#116]
![image](https://user-images.githubusercontent.com/9121359/58601445-21146700-825f-11e9-80a5-1d1358731a54.png)

Percebi que concordei de forma errada com o campo "studentId" na sala de aula.

Por questões de normalização e pelo fato de que as matérias ficam armazenadas para serem usadas posteriormente, o campo mencionado não existe. Haverá uma tabela a mais que liga estudantes a pendências.

**Comment by Jamadhar** [comment]
Queres dizer, assim?
![image](https://user-images.githubusercontent.com/29318425/58654112-929af680-82ed-11e9-8e7d-ca85c97d1eca.png)

**Comment by lubien** [comment]
Isso mesmo!
