### ISSUE TITLE
Erro ao salvar data de defesa em studentComboBox

### ISSUE THREAD

**Issue by Lakshamana** [projeto-spider/labes-2019#129]
Ao salvar a data de defesa no comboBox e apertar o botão de 'Atualizar' o modo de edição continua ativo, quando deve estar inativo.

**Comment by lubien** [comment]
Como atualmente **todos** os campos continuam editáveis após salvar, vou marcar isso inválido.

Se o cliente vir isso como problema, retomamos o assunto.
