### ISSUE TITLE
Parâmetros errados não são verificados na API

### ISSUE THREAD

**Issue by Lakshamana** [projeto-spider/labes-2019#144]
Ao enviar GET para /api/students/ com um parâmetro errado como em 
```
/api/students/?erro=true
```
o resultado é uma resposta com status 200 OK.

## Resultado Esperado: 
Resposta com status 400 Bad Request e corpo especificando o erro

## Resultado Atual:
Reposta com status 200 OK

**Comment by souzaluuk** [comment]
Não entra na questão do tratamento de colunas? @lubien

**Comment by souzaluuk** [comment]
Vou tentar resolver esta e a issue #50 em conjunto, por considerar q são correlacionadas.
