### ISSUE TITLE
Com implementação de Pendências, associar a meta de estudantes aptos e não aptos

### ISSUE THREAD

**Issue by souzaluuk** [projeto-spider/labes-2019#150]

**Comment by lubien** [comment]
Pode especificar isso e dizer se já está sendo feito?

**Comment by lubien** [comment]
Implementado em #240 pro Backend

Confirma que foi implementado no front @urielfcampos, diz a PR e fecha aqui.

**Comment by lubien** [comment]
Graduandos não tem pendências, logo não tem associação.
