### ISSUE TITLE
O campo "prescribed" é inútil pois a verificação é feita no documento de prescrição.

### ISSUE THREAD

**Issue by quaresmateo** [projeto-spider/labes-2019#156]

**Comment by lubien** [comment]
@Jamadhar pode verificar isso?

**Comment by Jamadhar** [comment]
O documento de prescrição não vai ser gerado a partir dos alunos prescritos?

**Comment by lubien** [comment]
Sim, mas ele fica na tabela de documentos. A tabela aluno tem "prescribed" que não está sendo usado.

**Comment by Jamadhar** [comment]
Pois é, mas não é necessário primeiro saber que o aluno está prescrito, para depois criar o documento?

**Comment by Jamadhar** [comment]
Conversei com o lucas e ele me explicou como deve funcionar a lista de prescrição. Já está corrigido.

**Comment by lubien** [comment]
Já que o @souzaluuk já tá inteirado, verifica q o campo não existe e pode fechar q issue
