### ISSUE TITLE
Zerar pendências quando virar graduando

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#182]
Dica: na importação do CSV

**Comment by souzaluuk** [comment]
Isso vale apenas pros registros da tabela `Pendency`?
Ou tenho q alterar status de cd e coisas assim?

**Comment by souzaluuk** [comment]
@jairofilho79 pega que é tua

**Comment by lubien** [comment]
@jairofilho79 onde está sua PR?

**Comment by lubien** [comment]
@lubien // @Jpredador79

**Comment by souzaluuk** [comment]
@lubien @Jpredador79 , deu certo?
