### ISSUE TITLE
Alterações na confirmação de listas de email

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#184]
- [ ] Confirmar alguns alunos (receber ids de quem confirma).
- [ ] Separar confirmações de entrada e saída.

**Comment by lubien** [comment]
Se isto tiver sendo feito, mudar a arraia no kanban @souzaluuk @Lakshamana

**Comment by lubien** [comment]
@souzaluuk já acabou o backend disso? Se sim, por que não referenciou essa issue? Tem que remover a label Backend daqui?

**Comment by souzaluuk** [comment]
Implementado em #306
