### ISSUE TITLE
Adicionar curso e forma de ingresso nos formulários

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#186]

**Comment by Jamadhar** [comment]
Vocês já estão usando algum nome específico para esses dois campos?

**Comment by lubien** [comment]
> Vocês já estão usando algum nome específico para esses dois campos?

O jairo usou

```js
table
      .enum('course', ['cbcc', 'cbsi'])
      .notNullable()
    table
      .enum('admissionType', ['?', '?'])
      .notNullable()
```

**Comment by Jamadhar** [comment]
Ok, adicionado.

**Comment by jairofilho79** [comment]
table
      .enum('course', ['cbcc', 'cbsi', 'other'])
      .notNullable()
table
      .enum('admissionType', ['psufpa', 'sisu', 'other'])
      .notNullable()

@Jamadhar

**Comment by souzaluuk** [comment]
@jairofilho79 Atualize na WIKI

**Comment by jairofilho79** [comment]
@souzaluuk Done.

**Comment by souzaluuk** [comment]
@jairofilho79 Faltou aqui https://github.com/projeto-spider/labes-2019/wiki/API:-Solicitation, caso vc tenha mexido na tabela de Solicitations
