### ISSUE TITLE
Definir favicon

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#197]

**Comment by urielfcampos** [comment]
Vou mandar isso aqui pro pessoal de gerência.

**Comment by JoaoPedroMoraes** [comment]
![Captura de Tela_selecionar área_20190703142439](https://user-images.githubusercontent.com/46731099/60612300-a7f8ba00-9d9e-11e9-924b-c391ad631ea5.png)
Que tal? :grimacing:

**Comment by lubien** [comment]
:clap:

**Comment by lubien** [comment]
@JoaoPedroMoraes consegue fazer como .ico 16x16?

**Comment by lubien** [comment]
// @JoaoPedroMoraes

**Comment by JoaoPedroMoraes** [comment]
> // @JoaoPedroMoraes

[ARTE.zip](https://github.com/projeto-spider/labes-2019/files/3362849/ARTE.zip)
O arquivo compactado tem o logo em formato de SVG, PNG e FAVICON. :+1:
