### ISSUE TITLE
Criar serviço para fazer requisições HTTP

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#204]
[Nuxt plugins](https://nuxtjs.org/guide/plugins/)
[Nuxt Modules](https://nuxtjs.org/guide/modules)

**Comment by lubien** [comment]
Imagino que modulos sejam mais do que precisamos.

Já com plugins poderíamos injetar em um escopo (`this.$api`?) as funções.

Uma regras deveriam ser seguidas para manter o código limpo como por exemplo:

1. O mundo externo da função não precisa saber como a requisição é feita.
2. Os argumentos são pegos na mão para evitar casos inesperados.
3. Todas as funções simplesmente retornam uma promise.

Algo mais?

**Comment by urielfcampos** [comment]
Acredito que estas regras sejam suficientes, caso apareça mais a gente coloca aqui.
