### ISSUE TITLE
Criar opção de voltar, cancelar ou ir pra home na tela de cadastro de defesa de TCC

### ISSUE THREAD

**Issue by souzaluuk** [projeto-spider/labes-2019#208]

**Comment by souzaluuk** [comment]
@quaresmateo 
Aqui tbm, sobre o que mencionei com vc hj cedo.

**Comment by quaresmateo** [comment]
Adicionado em 8834996370a292e62622df94af615fc0399bd06c e e55bdd416a89e90802e99cfaffdc22c68e0cfd98
