### ISSUE TITLE
Limitar data mínima no cadastro de defesa de TCC

### ISSUE THREAD

**Issue by souzaluuk** [projeto-spider/labes-2019#209]
Atualmente no front eu consigo selecionar datas passadas do dia em questão.

**Comment by souzaluuk** [comment]
@quaresmateo 
Aproveita pra ver isso, afinal vc está mexendo nessa page.

**Comment by quaresmateo** [comment]
Feito em 0106f5cdc8176444b79e94158163f6285ce63dc3
