### ISSUE TITLE
Meta 09 não está clara

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#21]
Documento está vago e aparenta ter semelhança com a US04 da meta 01.

**Comment by fallennabicicleta** [comment]
Fala, João, a meta 9 trata da forma como vamos alimentar o sistema com as informações presentes no email google, ou seja, pegar a lista de participantes do grupo principal e adicionar ela na ferramenta para a realização de outras funções por exemplo, com a alteração de requisitos que houve possivelmente teria que alterar algo, mas a lógica a principio permanece a mesma. Abraço

**Comment by lubien** [comment]
Estamos trabalhando com o CSV do google na Meta 1 agora mesmo.

Verificamos que o máximo que podemos fazer com esse CSV é encontrar emails pareados do SIGAA e do Groups e marcar alunos que não foram pareados (usando a coluna "Comentário").

Acaba que a meta 9 fica bem vazia devido as mudanças que tivemos.

**Comment by fallennabicicleta** [comment]
Ah sim, entendo, mas de certa forma, a lista vindo do SIGAA com o email é apenas para os alunos ativos, os concluintes e calouros ficariam de fora dessa comparação devido não termos o email deles.

**Comment by lubien** [comment]
Meta removida
