### ISSUE TITLE
A fonte alterada pelo documento anterior na geração de pdf interfere no próximo documento

### ISSUE THREAD

**Issue by daniel-santana** [projeto-spider/labes-2019#217]
O maior problema é a organização do texto nos documentos, usando o Cd como exemplo, quando ele é gerado junto com os outros documentos, tudo aparece corretamente alinhado, mas caso apenas ele seja gerado, algumas fontes mudam (estilo da fonte, negrito).

**Comment by lubien** [comment]
Como tá isso aqui?
