### ISSUE TITLE
Defesas somem misteriosamente da página inicial do professor

### ISSUE THREAD

**Issue by quaresmateo** [projeto-spider/labes-2019#218]
É necessário atualizar a página para que as defesas apareçam. Isso acontece na página de defesas do adm também.

**Comment by quaresmateo** [comment]
#194

**Comment by souzaluuk** [comment]
O filtro já está respondendo adequadamente no back.
O mesmo vale para a issue #219

**Comment by lubien** [comment]
Qual a situação aqui @souzaluuk , o que falta? O que diz respeito a eu ser atribuído?

**Comment by souzaluuk** [comment]
Bem, não sei pq o snr foi atribuído.
Mas basicamente ficou apenas pro front.
A não ser q o @quaresmateo diga diferente.

**Comment by urielfcampos** [comment]
Como reproduzir:

**Tenha defesas no professor antes de fazer isso.**

1. Logue como professor. Note que não há curso selecionado, o padrão.
![image](https://user-images.githubusercontent.com/9121359/60689132-76f8b200-9e90-11e9-831e-f3fec763b29f.png)

Não há defesas.

2. Selecione o curso

![image](https://user-images.githubusercontent.com/9121359/60689139-8c6ddc00-9e90-11e9-91e7-5a16a32228b2.png)

Não há defesas.

3. Troque de páginas (Home -> Cadastro -> Defesa).

![image](https://user-images.githubusercontent.com/9121359/60689147-a4456000-9e90-11e9-9b6e-40f4a39a2fae.png)

Há defesas.

**Comment by souzaluuk** [comment]
Como está isso?

**Comment by lubien** [comment]
@souzaluuk isso é provavelmente ocasionado pelo fato de que o courseTag muda no front, mas não engatilha a atualização das listas.

**Comment by urielfcampos** [comment]
Vou fazer isso.

**Comment by lubien** [comment]
@urielfcampos 

https://t.me/c/1239077896/17483
