### ISSUE TITLE
Adicionar mensagem de erro para estar offline

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#225]

**Comment by souzaluuk** [comment]
O que ocorre aqui exatamente?

**Comment by lubien** [comment]
entre na aplicação normalmente, desligue a internet e veja que não vai avisar que está offline

**Comment by lubien** [comment]
// @urielfcampos

**Comment by souzaluuk** [comment]
Se trata apenas no front?

**Comment by lubien** [comment]
> Se trata apenas no front?

Sim
