### ISSUE TITLE
Formulário de login tem que aceitar enter mesmo estando no checkbox

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#227]
Verifique se existe um `<form>`

**Comment by urielfcampos** [comment]
Eu estava testando aqui o formulário de login aceita sim o enter, mesmo estando no checkbox.

**Comment by lubien** [comment]
@urielfcampos Quais navegadores?

**Comment by urielfcampos** [comment]
No firefox funcionou, no chrome não, no chrome o enter altera o status do checkbox.

**Comment by lubien** [comment]
@urielfcampos Será que usar um <form @submit.prevent="fn"> não resolve?

**Comment by urielfcampos** [comment]
resolveu.

**Comment by urielfcampos** [comment]
Vou alterar na minha próxima PR

**Comment by lubien** [comment]
@urielfcampos Faz uma individual owo
