### ISSUE TITLE
(Remover) campos que ninguém usa (ainda?)

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#231]
Quais as justificativas?

Remover os marcados

- [x] `isUndergraduate` (temos isConcluding, que é o inverso)
- [x] `termPaper` (sinto que será usado)
- [x] `recordSigned` (?)
- [x] `note` (da defesa?)
- [x] `entryDate` (?)

**Comment by lubien** [comment]
@lubien // @onetwoLXIV @urielfcampos @quaresmateo @Lakshamana @souzaluuk

**Comment by Jamadhar** [comment]
- "_isUndergraduate_" era usado para avaliar o aluno graduando, acredito que agora esteja sendo verificado por "_isGraduating_".

- "_termPaper_" era a verificação da entrega da lauda, agora está sendo verificado diretamente na tabela "_DOCUMENT_"

- "_recordSigned_" era a verificação da assinatura da ata, também está sendo verificado em "_DOCUMENT_"

- "_note_" dizia respeito a uma nota, no sentido de observação, que ficaria associada ao aluno caso ele fosse apto e não estivesse no e-mail geral.

- "_entryDate_" era a data de entrada do aluno na faculdade, eu não lembro qual era a utilidade desse campo....

Todos os campos já haviam sido retirados da modelagem na ultima ou penúltima revisão.

**Comment by lubien** [comment]
@souzaluuk como você deu entrada, justo que você dê vazão.

**Comment by souzaluuk** [comment]
NOOOOOOOOOOOOOOOOO

**Comment by lubien** [comment]
Vo te dá essa ajuda @souzaluuk

**Comment by souzaluuk** [comment]
Não era pra fechar essa, @lubien ?
