### ISSUE TITLE
Modelagem de usuário necessita de um papel

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#24]
Pode ser um enumerável entre `admin` e `teacher`. Nome recomendado de campo: `role`.

**Comment by Jamadhar** [comment]
Ok, adicionado.
![Entidade Relacionamento](https://user-images.githubusercontent.com/29318425/57587334-d44c3480-74d9-11e9-9fb2-34d646bdca8f.png)

**Comment by lubien** [comment]
Perfeito
