### ISSUE TITLE
Não há aviso de erro ao colocar arquivo muito grande.

### ISSUE THREAD

**Issue by jairofilho79** [projeto-spider/labes-2019#246]
Creio que não é para arquivo grandes, e sim para qualquer erro.
Em vez de alerta o usuário, a aplicação para de funcionar.

Minha hipótese é que perde-se a referência do this, por isso não há o reconhecimento da função.

![image](https://user-images.githubusercontent.com/32720779/60632401-caf58f00-9ddb-11e9-8626-e40b6ae3796d.png)

**Comment by urielfcampos** [comment]
Isso foi no combobox ? no import students ? Qual o tamanho do arquivo ?

**Comment by lubien** [comment]
> Isso foi no combobox ? no import students ? Qual o tamanho do arquivo ?

// @jairofilho79

**Comment by urielfcampos** [comment]
Consegui resolver, está na PR #325
