### ISSUE TITLE
Remover botão de destaque acadêmico caso um já tenha sido selecionado.

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#252]

**Comment by urielfcampos** [comment]
Basta desabilitar o botão, não precisa retirar.

**Comment by lubien** [comment]
Provavelmente tem que ter um aviso na hora de escolher o destaque. 

"Não pode ser desfeito".

Pessoalmente acredito que desabilitar é perigoso

**Comment by urielfcampos** [comment]
é ideia do cliente.

**Comment by jairofilho79** [comment]
Já foi feito?

**Comment by lubien** [comment]
Ninguém se voluntariou. Acho que não. Se quiser, dá assigned aí.
