### ISSUE TITLE
Alterações componete lista de email

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#254]
- **Pagina de lista de email**
    - [x] Separar as abas de alteração em componentes separados: Alterações de inserção e Alterações de remoção
    - [x] refatorar componente para possuir um checkbox e confirmar as alterações só de alunos selecionados
    - [x] Possivelmente retirar as listas já que saiu do escopo.

**Comment by lubien** [comment]
Removendo label Backend pois já está no master
