### ISSUE TITLE
Especificar o que pode/deve ser editado na meta 07

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#27]

**Comment by fallennabicicleta** [comment]
Bom dia, João,tudo bem? Segue a US específica para essa edição e suas respectivas business rules:
US6: Selecionar campo que deseja alterar🔴(baixa)
BR01: Em CD, Ata, Lauda e Lista de Prescrição deve haver um checkbox
BR02: Em CRG, Orientador e matérias pendentes deve haver um campo para digitar a informação

**Comment by lubien** [comment]
Adicionado!
