### ISSUE TITLE
Professores não podem ver documentos no combo box da defesa

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#270]
![image](https://user-images.githubusercontent.com/9121359/60689058-d0acac80-9e8f-11e9-963f-a352ddd2106c.png)

Sugestão: v-if na coluna direita usando uma prop que diga que é a visualização do professor.

[KISS](https://en.wikipedia.org/wiki/KISS_principle)

**Comment by lubien** [comment]
Tudo ok aqui @quaresmateo ?

**Comment by quaresmateo** [comment]
@lubien Estou fazendo isso agora
