### ISSUE TITLE
Atualizar defesas do professor quando ele logar.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#272]
Como reproduzir:

**Tenha defesas no professor antes de fazer isso.**

1. Logue como professor. Note que não há curso selecionado, o padrão.
![image](https://user-images.githubusercontent.com/9121359/60689132-76f8b200-9e90-11e9-831e-f3fec763b29f.png)

Não há defesas.

2. Selecione o curso

![image](https://user-images.githubusercontent.com/9121359/60689139-8c6ddc00-9e90-11e9-91e7-5a16a32228b2.png)

Não há defesas.

3. Troque de páginas (Home -> Cadastro -> Defesa).

![image](https://user-images.githubusercontent.com/9121359/60689147-a4456000-9e90-11e9-9b6e-40f4a39a2fae.png)

Há defesas.

**Comment by quaresmateo** [comment]
Essa issue já foi aberta como #218

**Comment by lubien** [comment]
Opa, passa essas inforamções pra lá e fecha essa?

**Comment by urielfcampos** [comment]
Informações repassadas para #218
