### ISSUE TITLE
Verificar a nota antes de finalizar defesa

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#273]
Seja uma defesa **aceita**. Para deixar o admin finalizar ela, **verifique** que ela **já tem nota**, senão, não deixe.

![image](https://user-images.githubusercontent.com/9121359/60689234-74e32300-9e91-11e9-8ed7-4307c294dc52.png)

**Comment by daniel-santana** [comment]
Caso seja feita uma atualização onde o status seja "done" mas a defesa não tenha nota, retorna status 422 e código de erro 'MISSING_GRADE'
