### ISSUE TITLE
Defesas podem ser apagadas SE não forem "Realizadas"

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#274]
Apenas Pendentes e Aceitas

**Comment by lubien** [comment]
Fazendo o backend disso agora

**Comment by jairofilho79** [comment]
João. Como vai funcionar isso aqui? O Alan vai poder deletar a defesa a hora que ele quiser, desde que ela não tenha sido realizada? Isto é, haverá um botão?

**Comment by lubien** [comment]
@jairofilho79 Exatamente oq tu falou. Crie um botão
