### ISSUE TITLE
Mover botão "Eleger Destaque Acadêmico"

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#276]
Colocar perto dos graduandos aptos, já que remete a eles.

![image](https://user-images.githubusercontent.com/9121359/60689284-22563680-9e92-11e9-93b9-ab385600e059.png)

**Comment by quaresmateo** [comment]
Tem que fazer isso realmente? Se sim, vai ter que mover esse botão pra dentro do component SearchInput :thinking: @lubien

**Comment by urielfcampos** [comment]
@quaresmateo Não tem como criar um slot pra inserir ?

**Comment by lubien** [comment]
> @quaresmateo Não tem como criar um slot pra inserir ?

🔝

**Comment by quaresmateo** [comment]
Ainda não mexi com slots. Preciso dar uma lida sobre isso.

**Comment by urielfcampos** [comment]
@quaresmateo https://br.vuejs.org/v2/guide/components-slots.html
