### ISSUE TITLE
Mover botão da Lista de Prescrição para a sidebar

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#279]
![image](https://user-images.githubusercontent.com/9121359/60689313-8ed13580-9e92-11e9-8692-96982d53f856.png)

// @ianCamposs se liga nessa

**Comment by quaresmateo** [comment]
Onde exatamente isso deve ficar ? Dentro de grupos de email ?

**Comment by ianCamposs** [comment]
A lista de prescrição é interessante pro grupo de maior controle(formandos), então na minha opinião seria interessante manter ela nessa página mesmo

**Comment by lubien** [comment]
> A lista de prescrição é interessante pro grupo de maior controle(formandos), então na minha opinião seria interessante manter ela nessa página mesmo

Isso não foi um pedido. Só estamos informando o que o cliente quer.

**Comment by lubien** [comment]
> Onde exatamente isso deve ficar ? Dentro de grupos de email ?

Antes parece melhor
