### ISSUE TITLE
Criar página de configurações globais

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#282]
- Configurar nome do diretor do ICEN, exemplo: "Prof(a). Dr(a). Josivoldo Oroojo"
- Configurar nome do diretor do FACOMP, exemplo: "Prof(a). Dr(a). Morcos Montoiro Donoz"
- Configurar período atual, exemplo: "2018.2"

**Comment by lubien** [comment]
// @daniel-santana daqui que vem o que tu pediu

**Comment by urielfcampos** [comment]
Vou começar a fazer o front.

**Comment by daniel-santana** [comment]
Coloquei um exemplo de como ficaria o nome do diretor. Também precisa ter o nome do diretor da FACOMP
