### ISSUE TITLE
Confirmar o período antes de gerar certificados

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#283]
Relacionado a #281 e #282 

Quando for gerar certificados, mostre o período configurado globalmente e em seguida pergunte se está certo

**Comment by urielfcampos** [comment]
primeiro é necessário fazer #282

**Comment by Lakshamana** [comment]
Nesse caso, assim que o usuário disparar o botão Enviar do formulário de defesa deve aparecer um diálogo confirmando com ele o período em questão ou podendo editar, entendi certo?

**Comment by lubien** [comment]
> Nesse caso, assim que o usuário disparar o botão Enviar do formulário de defesa deve aparecer um diálogo confirmando com ele o período em questão ou podendo editar, entendi certo?

Dispara a confirmação. Se tiver errado, manda pra página de configurações globais.

O cliente não queria tanto isso, mas se não houver a confirmação, um grave erro pode ser cometido então convencemos ele.

**Comment by Lakshamana** [comment]
Mas o professor pode editar campos da página de configurações globais?

**Comment by lubien** [comment]
@Lakshamana Professor não faz isso, só admin

**Comment by Lakshamana** [comment]
@lubien Pois é, do jeito que tu disseste me levou a entender que ele vai editar o período nas configurações globais. Pq pelo que eu testei os documentos são gerados logo que o professor dispara o Enviar

**Comment by urielfcampos** [comment]
Acho que teve um certa confusão aqui, estes são os certificados de conclusão de curso, que só o admin pode gerar, na pagina de `formandos`.

**Comment by Lakshamana** [comment]
Ah, saquei.

**Comment by lubien** [comment]
Período não é usado em nenhum lugar em nenhum certificado.
