### ISSUE TITLE
Formulário de tcc : Alterações

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#285]
- [x] Limitar quantidade de alunos para no máximo 2
- [x] Orientador ou coorientador podem ser externos mas apenas 1 deles.
- [ ] Em titulação, se a opção "Outros" for escolhida, abrir input para digitar a titulação.
- [x] Adequar tamanho do text area.

**Comment by Lakshamana** [comment]
@urielfcampos, quanto ao 3º item: conversei com @lubien e chegamos à conclusão de que isso demandaria de pessoas de back e frontend só pra isso. Resolvemos aplicar forças em coisas mais urgentes.
Quanto ao quarto item, falta especificar o efeito desejado da text area.
Contudo os dois primeiros itens foram trabalhados

**Comment by urielfcampos** [comment]
Temos que conversar com o cliente então, a text area tem que checar na planilha que ele mandou pra gente e ver o tamanho máximo dos resumos lá para poder adequar. @Lakshamana
