### ISSUE TITLE
Adicionar campo booleano `isTeacher` para banca examinadora

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#286]
É preciso saber se as pessoas da banca são professores ou não para adequar os documentos gerados.

**Comment by lubien** [comment]
Todos ou individualmente?

**Comment by urielfcampos** [comment]
@lubien Individualmente

**Comment by Jamadhar** [comment]
Os campos advisorType, coAdvisorType e evaluatorType não tem esse objetivo?

**Comment by lubien** [comment]
@Jamadhar isso só contempla o fato de ser interno ou externo, o que impacta na geração de credenciais (para externos).

A ideia de dizer que é professor é para incrementar no PDF. Algo como: `Professor Dr.(a) Sandro` para professores ou `Dr.(a) Abobrinha` para não professores.

Vale salientar essa parte do PDF a quem editará.

// @daniel-santana

**Comment by lubien** [comment]
Renomeei o título para evitar confusões

**Comment by Jamadhar** [comment]
Esses campos se aplicam a todos os membros da banca, incluindo orientador e coorientador?

**Comment by lubien** [comment]
> Esses campos se aplicam a todos os membros da banca, incluindo orientador e coorientador?

![image](https://user-images.githubusercontent.com/9121359/60742578-483c1380-9f44-11e9-93d7-15b3e2279a34.png)

**Comment by Jamadhar** [comment]
Adicionado.

![image](https://user-images.githubusercontent.com/29318425/60742723-dadcb280-9f44-11e9-8833-f6e4e7479008.png)

**Comment by urielfcampos** [comment]
Falta só o front disso ?

**Comment by lubien** [comment]
@urielfcampos O @Jpredador79 n começou isso?

**Comment by urielfcampos** [comment]
não sei, vou confirmar com ele quando ele acordar.

**Comment by lubien** [comment]
@urielfcampos Da uma olhada ai

**Comment by lubien** [comment]
Backend já está no master
