### ISSUE TITLE
 Mesmo o aluno CANCELADO, pode defender o TCC.

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#307]
Também, às vezes, o aluno chegou no último bloco em que pode haver a defesa de tcc, mas ainda deve outras matérias, porém ele não está FORMANDO, mas ATIVO ainda, mas já está providenciando o TCC.
Ou seja, a busca por esse aluno, deve ser independente de qualquer STATUS, exceto "concluído", é claro.

**Comment by lubien** [comment]
https://github.com/projeto-spider/labes-2019/blob/master/components/DefenseForm.vue#L416-L430

Parece que já está sendo feito isso.

Verifica e fecha.

**Comment by lubien** [comment]
O combobox inclusive nem discrimina, ele só vê se tem defesa.

https://github.com/projeto-spider/labes-2019/blob/master/components/StudentComboBox.vue#L16-L32

**Comment by urielfcampos** [comment]
@lubien Perfeito

**Comment by jairofilho79** [comment]
Foi fechado/feito?

**Comment by lubien** [comment]
// @urielfcampos

**Comment by urielfcampos** [comment]
Pelo o que vi, já está implementado.
