### ISSUE TITLE
Adicionar filtros no componente de pesquisa de alunos

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#31]
- [x] Filtro por curso (padrão)
- [x] Filtro por status
- [x] Filtro por nome
- [x] Filtro por matricula

**Comment by lubien** [comment]
@souzaluuk isso já está pronto e no master, certo?

**Comment by lubien** [comment]
Qual o estado disso @quaresmateo ?

**Comment by souzaluuk** [comment]
Todos os filtros estão no master, funcionais e com testes unitários.
Atenção para o filtro por status que deve ser solicitado a API por meio das flags: isActive, isConcluding, e etc.

**Comment by lubien** [comment]
Concluído visto que foi implementado no searchInput.vue
