### ISSUE TITLE
Usar *IsTeacher no modelo de divulgação

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#315]
Depende de #286

**Comment by jairofilho79** [comment]
@urielfcampos 
![image](https://user-images.githubusercontent.com/32720779/60758005-1086a780-9fe8-11e9-8c89-753870719528.png)
Só o Orientador tem o título, tipo e professor escondido pelo forceDisable. Está certo isso? Todos deveriam ser escondidos (aparace quando edita) ou todos deveriam aparecer? Ou beleza assim?

**Comment by urielfcampos** [comment]
Todos deveriam aparecer. @jairofilho79
