### ISSUE TITLE
Após marcar uma defesa, o autocomplete ainda indica o mesmo aluno, cuja defesa foi marcada.

### ISSUE THREAD

**Issue by jairofilho79** [projeto-spider/labes-2019#317]
Após marcar uma defesa, o autocomplete ainda indica o mesmo aluno.

**Comment by lubien** [comment]
@jairofilho79 Pode mostrar como reproduzir?

**Comment by jairofilho79** [comment]
Eu cadastrei uma defesa, CBSI (Laura Cardoso), tudo direitinho. Confirmei. Depois, na mesma tela, depois do aviso de sucesso. Eu fui cadastrar outro aluno, mas tentei o mesmo e ele me permitiu usar o mesmo aluno. Porém, na hora de concluir, houve um erro. Não foi especificado qual, mas creio que não foi permitido cadastrar para mais de 1 aluno no back-end.
