### ISSUE TITLE
Adicionar a wiki todas as rotas da API

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#33]

**Comment by souzaluuk** [comment]
Rotas para users e students incluídas na [página da Wiki](https://github.com/projeto-spider/labes-2019/wiki/Lista-de-rotas-da-API).
Faltam as demais.

**Comment by souzaluuk** [comment]
Rotas para documents incluídas.

**Comment by lubien** [comment]
https://github.com/projeto-spider/labes-2019/wiki/API-REST
