### ISSUE TITLE
Erro na geração de certificado 

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#356]
`http://localhost:3000/api/students/8/attendance-register?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZnVsbE5hbWUiOiJBZG1pbmlzdHJhZG9yIiwiZW1haWwiOiJhZG1pbkBkb21haW4uY29tIiwicm9sZSI6ImFkbWluIn0sImV4cCI6MTU2MjcyMTE5NCwiaWF0IjoxNTYyNjM0Nzk0fQ.zgLlKHdJxQStkvzb3w9g1Vb1-WrTebqii6JvIql8Tis`

**Comment by souzaluuk** [comment]
Quem pegou essa?

**Comment by urielfcampos** [comment]
@souzaluuk Até agora ninguém.

**Comment by urielfcampos** [comment]
Implementado direto no master
