### ISSUE TITLE
Atualizar tabela de aluno

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#41]
Data de ingresso no grupo de email, 
Orientador
Data de defesa do tcc

**Comment by lubien** [comment]
@urielfcampos O professor não ia ser um usuário?

**Comment by urielfcampos** [comment]
Atualizado

**Comment by lubien** [comment]
Mas o professor não ia ser um **usuário**?

**Comment by lubien** [comment]
Então essa issue é pra aluno? Saquei

**Comment by urielfcampos** [comment]
Sim

**Comment by lubien** [comment]
A coluna orientador não é melhor deixar pra quando formos fazer as metas relacionadas aos professores mexerem na plataforma?

**Comment by fallennabicicleta** [comment]
A ideia seria do orientador ser apenas uma informação interna do combox de informações de quando se cicla no aluno, não necessitando uma coluna para o mesmo. (O cliente recuou sobre ideias extras sobre orientador, como por exemplo, listar alunos que possuem orientador X).

**Comment by Jamadhar** [comment]
Adicionei os campos de data de defesa e data de ingresso. Como o campo orientador ainda está meio obscuro e não temos metas neste ciclo que façam o utilizem, resolvi não adicionar no momento.

**Comment by souzaluuk** [comment]
Reabrindo por se relacionar com #78 e alinhar modelo do banco com a implementação.

**Comment by lubien** [comment]
@Jamadhar notamos que existe `defenseDate` e `defendedIn`. Pode esclarecer a diferença, se existe?

**Comment by Jamadhar** [comment]
Foi um erro na modelagem, já está corrigido.

**Comment by souzaluuk** [comment]
@Jamadhar , em relação e versão anterior da tabela de estudantes:
- campos retirados:
    isForming (Está correto essa retirada?)
- campos adicionados:
    entryDate
    note
    advisor
    defenseDate
    term
    recordSigned
    termPaper
    cd
    isUndergraduate

** O campo `pendencies` ainda não será inserido, visto que a abordagem sugerida é que pendencias possa ter crud, logo ser uma tabela no nosso db.
