### ISSUE TITLE
Aceitação da utilização de formulários para ingresso no grupo de calouros e grupo principal de email

### ISSUE THREAD

**Issue by ianCamposs** [projeto-spider/labes-2019#46]
O Alan aceitou que utilizemos formulários para receber as solicitações de entrada no grupo de calouro e principal.

**Comment by lubien** [comment]
Opa. Podes dizer como isso impacta nas próximas metas e até mesmo nas anteriores?

**Comment by fallennabicicleta** [comment]
Posso sim, primeiramente falando dos calouros, acredito que possamos alimentar a lista de email deles apenas utilizando as novas requisições via formulário e não mais tendo que por um arquivo extraído do grupo de calouros do google.(Precisamos conversar com vocês de implementação sobre isso pra ver qual a melhor solução). Além disso, quanto a solicitação para entrar no grupo principal, existem dois pontos, o primeiro é, considerando que a lista de alunos ativos vinda do SIGAA possui o email do aluno(podendo ser gmail ou não), quem tiver gmail será adicionado, porém se um aluno alterar esse email dele no sigaa de um hotmail para um gmail, por exemplo, quando o Alan atualizar a lista vinda do sigaa, o aluno será adicionado. Outro ponto é caso o aluno queria participar do grupo com um email alheio ao do sigaa, dessa forma, ele preencheria o formulário com o gmail, o sistema verificaria se o nome e matrícula estão ok e adicionaria o email passado pelo formulário. Ainda preciso trabalhar nessas metas(alterações e possíves criações de novas) (prova do Saraiva que me impede)

**Comment by fallennabicicleta** [comment]
Acredito que isso não impactará diretamente na meta 1, mas sim em uma meta futura.

**Comment by lubien** [comment]
Tudo bem. Conversamos quando acabar a prova então.

**Comment by lubien** [comment]
Aceito conforme #94
