### ISSUE TITLE
Tratar colunas inválidas em requisições

### ISSUE THREAD

**Issue by daniel-santana** [projeto-spider/labes-2019#50]
Error: SQLITE_ERROR: no such column:

**Comment by lubien** [comment]
Possível solução

https://github.com/bookshelf/bookshelf/issues/39#issuecomment-21085113

**Comment by lubien** [comment]
CRG aparentemente aceita varchar

**Comment by urielfcampos** [comment]
Isso aqui já foi finalizado ?
