### ISSUE TITLE
Normalizar nomenclatura de atributos das tabelas do BD.

### ISSUE THREAD

**Issue by souzaluuk** [projeto-spider/labes-2019#51]
Para mantermos a coerência entre os modelos e o que está sendo implementado, utilizar como padrão para definição da modelagem ( minúsculoSeguidoDeMaiúsculo ):

Nome de tabelas:
```
students, documents, users...
```
Atributos:
```
id, name, studentId, type, crg, cd, url...
```

**Comment by Jamadhar** [comment]
Corrigido.

**Comment by souzaluuk** [comment]
Show
@lubien 
Como faz pra atualizar o modelo que estávamos usando?

**Comment by lubien** [comment]
@souzaluuk manda num comentário a versão atualizada

**Comment by lubien** [comment]
Implementado em #48
