### ISSUE TITLE
Definir licença

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#61]

**Comment by lubien** [comment]
Como o pessoal de gerência resolveu se abster desta escolha @souzaluuk tem como tu fazer uma PR com a tua licença favorita?

**Comment by quaresmateo** [comment]
@lubien Peguei um susto. Pensei que já tinha começado a sprint 😥

**Comment by lubien** [comment]
@quaresmateo a sprint começa onde a outra termina, é a gente que quer acreditar que o __sistema__ deu uma folga.
