### ISSUE TITLE
Modelagem de Dados dos Estudantes (coluna isForming)

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#7]
Para a meta #5 precisa-se diferenciar alunos ativos, formandos, graduandos, cancelados  e concluídos.

[A atual modelagem](https://user-images.githubusercontent.com/9121359/57269668-b0629c00-705e-11e9-88a5-fbea24a06c9f.png) não possui uma flag para formandos.

**Comment by Jamadhar** [comment]
Resolvido. A modelagem geral do banco já foi adicionada ao drive. Segue a imagem da modelagem.
![v1 0](https://user-images.githubusercontent.com/29318425/57495784-1b51e400-72a6-11e9-9f90-111cb05de8f8.png)

**Comment by lubien** [comment]
Perfeito. Vou fechar a issue então.
