### ISSUE TITLE
Coluna de status nas tabelas de listagem

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#72]

**Comment by jairofilho79** [comment]
O que seria esse status?
Tabelas de listagem são aquelas que contém os alunos? (Alunos ativos e Alunos Totais)

**Comment by lubien** [comment]
Basicamente os alunos possuem diferentes possíveis status explicados na [Wikia](https://github.com/projeto-spider/labes-2019/wiki/API:-Student#flags).

Seu trabalho é identificar o status e mostrar no componente que acredito que se chama searchInput.

**Comment by jairofilho79** [comment]
Acho que essa vai ter que ser um pouco mais profunda, porque vai ter que filtrar pelo status também, né?

**Comment by lubien** [comment]
@jairofilho79 Os filtros já existem e podem ser evidenciados na wikia se o @souzaluuk documentou, seu trabalho seria (baseado na wikia e nas flags de cada aluno) determinar o status. Qualquer dúvida estou a disposição.

**Comment by lubien** [comment]
Implementado em #84
