### ISSUE TITLE
Adicionar informações adicionais no modal dos usuários

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#78]
- [x] Orientador
- [x] Data de Defesa
- - [x] Deve ser renomeado para “Defendeu em” caso o aluno esteja na lista de formandos (graduando-apto, graduando-não apto ou formando).
- [x] Edição de email (ver #94)

**Comment by lubien** [comment]
Editado para contemplar a edição do email como visto em #94.

**Comment by quaresmateo** [comment]
Estou aguardando a atualização do banco da tabela de alunos para poder adicionar as informações ao combo box.

**Comment by lubien** [comment]
Implementado em #128
