### ISSUE TITLE
Importação de estudantes do tipo "Graduando"

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#8]
No CSV de exemplo haviam alunos com status "ATIVO", "FORMANDO", "CONCLUÍDO" e "CANCELADO". Supostamente existe o status "GRADUANDO" e o código assume esta string porém não existem evidências concretas disso.

**Comment by lubien** [comment]
Atualmente não existe nenhum estudante com este status para confirmar o termo.

**Comment by fallennabicicleta** [comment]
Fala, João, o status "GRADUANDO" existe, porém na lista que nos foi disponibilizada por ser atual não possui nenhum aluno com esse status no momento. Abraço.

**Comment by lubien** [comment]
Estamos usando o termo, sim

**Comment by urielfcampos** [comment]
Segundo Sandro e com confirmação do cliente, vamos assumir que existe.
