### ISSUE TITLE
Inconsistência em Solicitation

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#88]
- [x] `Solicitation.registration` é um campo inteiro, diferente do `Student.registrationNumber` que é uma string. 
- [x] Vale salientar que a diferença entre as supracitadas nomenclaturas é tendenciosa.
- [x] `Solicitation.reason` originalmente remete à ideia de que os alunos escreviam a matrícula no campo de razão. Não precisamos pois a entrada não é filtrada (ver #94).

**Comment by lubien** [comment]
Conversamos com o @ianCamposs, o reason é válido, vamos precisar na implementação por questões históricas agora que sabemos que qualquer um entra na lista.

**Comment by lubien** [comment]
Visto as alterações de #94 o campo `Solicitation.reason` não é contemplado pois não há triagem de solicitações. Solicitamos que seja retirado.

**Comment by lubien** [comment]
Relacionado a #66

**Comment by Jamadhar** [comment]
Corrigido.

**Comment by Jamadhar** [comment]
![image](https://user-images.githubusercontent.com/29318425/58376484-b9021000-7f42-11e9-88a7-d1602fa1194c.png)

**Comment by Jamadhar** [comment]
![image](https://user-images.githubusercontent.com/29318425/58376486-c3240e80-7f42-11e9-8b18-452e34e643cf.png)

**Comment by lubien** [comment]
@AndreMP93 	@Lakshamana
