### ISSUE TITLE
Solicitations não referencia qual lista a pessoa deseja

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#93]
Na meta 3, as solicitações são de alunos concluintes. Na meta 2, as solicitações são de calouros.

O ER atual não evidencia qual é a lista em questão.

**Comment by Lakshamana** [comment]
@lubien Fiquei com muita dúvida nisso também

**Comment by Jamadhar** [comment]
Corrigido.

**Comment by lubien** [comment]
![image](https://user-images.githubusercontent.com/9121359/58368455-b44a4700-7ec3-11e9-94a4-8f315a582cbe.png)
