### ISSUE TITLE
Atualizações dos requisitos referentes a Sprint 3

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#94]
### Meta 16 foi absorvida pelas Metas 05 e 07.

Como a Meta 16 se tratava de usar email no combo box e as Metas 05 e 07 foram a definição do Combo Box, ocorreu a modificação das metas originais.

> BR: As informações são: Ata, CD, lauda, lista de prescrição, apresentadas em checkbox e CRG, orientador, data de defesa de TCC, email e matérias pendentes apresentadas em formato de texto.

Afetados: @souzaluuk e @quaresmateo 

### Alteração na definição de Aluno Ativo.

Alunos ativos são alunos cujo status no CSV seja: `ATIVO`, `FORMANDO` ou `GRADUANDO`.

Afetados: n/a.

### Meta 3 representa uma página de formulário enquanto a Meta 2 outra

O formulário deve ser feito de maneira com que seja utilizado em duas páginas diferentes (semelhante ao searchInput).

Na Meta 3, o formulário é para entrar no Newsletter. Na Meta 2, entrar na lista de calouros.

Afetados: @AndreMP93 e @Lakshamana 

### Metas 2 e 3 tem matrícula opcional

Devido ao fato de que calouros às vezes não tem matrícula e empresas podem pedir para participar, não deve-se forçar a necessidade de matrícula.

Afetados: @AndreMP93 e @Lakshamana 

### Metas 2 e 3 não tem "razão"

Como não haverá sistema de triagem, o campo "razão" foi inutilizado.

Afetados: @AndreMP93 e @Lakshamana

**Comment by lubien** [comment]
@lubien Sobre as revisões dos requisitos. Leiam essa issue.
PEssoas marcadas são os afetados.

**Comment by Lakshamana** [comment]
No caso desse componente compartilhado entre a meta 2 e 3, deve ser colocado um campo de escolha para saber a qual lista o interessado deve entrar (calouros ou newsletter)
